# Generated by Django 4.2.4 on 2023-08-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('size', models.DecimalField(decimal_places=10, max_digits=20)),
                ('product_id', models.CharField(max_length=50)),
                ('side', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
